import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Reads <cwd>/.atl/skill-registry.md when present. That file is a markdown
 * table generated by `gentle-ai skill-registry refresh`:
 *
 *   | Skill | Trigger / description | Scope | Path |
 *   | --- | --- | --- | --- |
 *   | `name` | description text | project | `/abs/path/SKILL.md` |
 *
 * We only ever read table rows out of it — never write, never inject its
 * full contents anywhere else.
 */

export interface RegistryEntry {
  name: string;
  description: string;
  path: string;
}

export function findRegistryPath(cwd: string): string | undefined {
  const candidate = path.join(cwd, ".atl", "skill-registry.md");
  return fs.existsSync(candidate) ? candidate : undefined;
}

export function readRegistry(registryPath: string): RegistryEntry[] {
  let raw: string;
  try {
    raw = fs.readFileSync(registryPath, "utf-8");
  } catch {
    return [];
  }

  const entries: RegistryEntry[] = [];
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed.startsWith("|")) continue;

    const cells = trimmed
      .slice(1, trimmed.endsWith("|") ? -1 : undefined)
      .split("|")
      .map((cell) => cell.trim());

    if (cells.length < 4) continue;

    const [rawName, rawDescription, , rawPath] = cells;
    if (rawName === undefined || rawDescription === undefined || rawPath === undefined) continue;

    // Skip header row ("Skill") and the separator row ("---").
    if (rawName === "Skill" || /^-+$/.test(rawName)) continue;

    const name = stripBackticks(rawName);
    const skillPath = stripBackticks(rawPath);
    if (!name || !skillPath) continue;

    entries.push({ name, description: rawDescription, path: skillPath });
  }
  return entries;
}

function stripBackticks(value: string): string {
  return value.replace(/^`+|`+$/g, "").trim();
}
